### ISSUE TITLE
Make the webpage responsive

### ISSUE THREAD

**Issue by HrutvikKhatkar** [pccoe-acm-hacktoberfest-2023/Art_circle-PCCOE_Hacktoberfest#1]

**Comment by pranav-lad** [comment]
Hey Hrutvik, this is Pranav Lad (CS'24), I would like to add this enhancement to the website. Kindly consider assigning this to me.
here's my profile: https://linktr.ee/pranavlad

**Comment by pccoe-acm** [comment]
@pranav-lad  i have assigned the task to you get it done and attach a screenshot or screen-recording for the issue
