### ISSUE TITLE
Update slider

### ISSUE THREAD

**Issue by HrutvikKhatkar** [pccoe-acm-hacktoberfest-2023/Art_circle-PCCOE_Hacktoberfest#3]
# Task :
Remove navigation bar and slider lines on bottom, which are reflecting above slider images.

**Comment by mugdhaK21** [comment]
Hey, this is Mugdha Kshirsagar here. I'm 2024 CS student from PCCOE. I would like to work on this issue. Kindly assign me the same.
Github Profile : https://github.com/mugdhaK21
LinkedIn Profile: - https://www.linkedin.com/in/mugdha-kshirsagar-6400a31ba/
