### ISSUE TITLE
Button style

### ISSUE THREAD

**Issue by HrutvikKhatkar** [pccoe-acm-hacktoberfest-2023/Art_circle-PCCOE_Hacktoberfest#4]
# Task :
More details button looks to simple so add some animated gesture to it.

**Comment by Fahass** [comment]
I want to work on this issue.

**Comment by mugdhaK21** [comment]
Hey Mugdha here, I would like to work on this issue. Can you please assign me the same?

**Comment by pccoe-acm** [comment]
@mugdhaK21  I have assigned it to you attach the screen shot once fixed

**Comment by mugdhaK21** [comment]
Yes sure, Thankyou!
